#ifndef C2C_TRANSFER_BEARLY_CONFIG_H
#define C2C_TRANSFER_BEARLY_CONFIG_H

#include <stdio.h>

#include "chip_config.h"
#include "transfer_proto.h"

#ifndef C2C_TRANSFER_BEARLY_LOG_ENABLE
#define C2C_TRANSFER_BEARLY_LOG_ENABLE 1
#endif

#if C2C_TRANSFER_BEARLY_LOG_ENABLE
#define C2C_TRANSFER_BEARLY_LOG(...) do { printf(__VA_ARGS__); } while (0)
#else
#define C2C_TRANSFER_BEARLY_LOG(...) do { } while (0)
#endif

#ifndef C2C_TRANSFER_BEARLY_TARGET_FREQUENCY_HZ
#define C2C_TRANSFER_BEARLY_TARGET_FREQUENCY_HZ 500000000ULL
#endif

#ifndef C2C_TRANSFER_BEARLY_SHARED_BASE
#define C2C_TRANSFER_BEARLY_SHARED_BASE TRANSFER_SHARED_BASE_ADDR
#endif

#ifndef C2C_TRANSFER_BEARLY_SHARED_BYTES
#define C2C_TRANSFER_BEARLY_SHARED_BYTES TRANSFER_SHARED_BYTES
#endif

#ifndef C2C_TRANSFER_BEARLY_MAILBOX_ADDR
#define C2C_TRANSFER_BEARLY_MAILBOX_ADDR C2C_TRANSFER_BEARLY_SHARED_BASE
#endif

#ifndef C2C_TRANSFER_BEARLY_NUM_PACKETS
#define C2C_TRANSFER_BEARLY_NUM_PACKETS 48u
#endif

#ifndef C2C_TRANSFER_BEARLY_INTERVAL_CYCLES
#define C2C_TRANSFER_BEARLY_INTERVAL_CYCLES 1000000ULL
#endif

#ifndef C2C_TRANSFER_BEARLY_WAIT_LOG_EVERY
#define C2C_TRANSFER_BEARLY_WAIT_LOG_EVERY 200000u
#endif

#ifndef C2C_TRANSFER_BEARLY_CLEAR_SHM_ON_BOOT
#define C2C_TRANSFER_BEARLY_CLEAR_SHM_ON_BOOT 1u
#endif

/* Start polling this many cycles before the predicted arrival cycle. */
#ifndef C2C_TRANSFER_BEARLY_SEARCH_INITIAL_SLACK_CYCLES
#define C2C_TRANSFER_BEARLY_SEARCH_INITIAL_SLACK_CYCLES 200000ULL
#endif

/* Step size used by the adaptive early/late search. */
#ifndef C2C_TRANSFER_BEARLY_SEARCH_INITIAL_STEP_CYCLES
#define C2C_TRANSFER_BEARLY_SEARCH_INITIAL_STEP_CYCLES 100000ULL
#endif

#ifndef C2C_TRANSFER_BEARLY_SEARCH_MIN_STEP_CYCLES
#define C2C_TRANSFER_BEARLY_SEARCH_MIN_STEP_CYCLES 1ULL
#endif

#ifndef C2C_TRANSFER_BEARLY_CACHE_LINE_BYTES
#define C2C_TRANSFER_BEARLY_CACHE_LINE_BYTES 64u
#endif

#ifndef C2C_TRANSFER_BEARLY_CACHE_EVICT_BYTES
#define C2C_TRANSFER_BEARLY_CACHE_EVICT_BYTES (256u * 1024u)
#endif

#ifndef C2C_TRANSFER_BEARLY_CACHE_EVICT_PASSES
#define C2C_TRANSFER_BEARLY_CACHE_EVICT_PASSES 3u
#endif

#endif /* C2C_TRANSFER_BEARLY_CONFIG_H */
