#ifndef C2C_BEARLY_SIMPLETEST_CONFIG_H
#define C2C_BEARLY_SIMPLETEST_CONFIG_H

#include <stdio.h>

#include "chip_config.h"
#include "simpletest_proto.h"

#ifndef BEARLY_SIMPLETEST_LOG_ENABLE
#define BEARLY_SIMPLETEST_LOG_ENABLE 1
#endif

#if BEARLY_SIMPLETEST_LOG_ENABLE
#define BEARLY_SIMPLETEST_LOG(...) do { printf(__VA_ARGS__); } while (0)
#else
#define BEARLY_SIMPLETEST_LOG(...) do { } while (0)
#endif

#ifndef BEARLY_SIMPLETEST_TARGET_FREQUENCY_HZ
#define BEARLY_SIMPLETEST_TARGET_FREQUENCY_HZ 500000000ULL
#endif

#ifndef BEARLY_SIMPLETEST_SHM_BASE
#define BEARLY_SIMPLETEST_SHM_BASE SIMPLETEST_SHARED_BASE_ADDR
#endif

#ifndef BEARLY_SIMPLETEST_SHM_BYTES
#define BEARLY_SIMPLETEST_SHM_BYTES SIMPLETEST_SHARED_BYTES
#endif

#ifndef BEARLY_SIMPLETEST_MAILBOX_ADDR
#define BEARLY_SIMPLETEST_MAILBOX_ADDR BEARLY_SIMPLETEST_SHM_BASE
#endif

#ifndef BEARLY_SIMPLETEST_RING_ADDR
#define BEARLY_SIMPLETEST_RING_ADDR (BEARLY_SIMPLETEST_MAILBOX_ADDR + sizeof(simpletest_mailbox_t))
#endif

#ifndef BEARLY_SIMPLETEST_RING_BYTES
#define BEARLY_SIMPLETEST_RING_BYTES (BEARLY_SIMPLETEST_SHM_BYTES - sizeof(simpletest_mailbox_t))
#endif

#ifndef BEARLY_SIMPLETEST_CACHE_LINE_BYTES
#define BEARLY_SIMPLETEST_CACHE_LINE_BYTES 64u
#endif

#ifndef BEARLY_SIMPLETEST_CACHE_EVICT_BYTES
#define BEARLY_SIMPLETEST_CACHE_EVICT_BYTES (512u * 1024u)
#endif

#ifndef BEARLY_SIMPLETEST_POLL_EVICT_EVERY
#define BEARLY_SIMPLETEST_POLL_EVICT_EVERY 1u
#endif

#endif /* C2C_BEARLY_SIMPLETEST_CONFIG_H */
