#!/usr/bin/env python3
"""Generate per-type MFCC golden header by parsing mfcc-test output.txt."""

from __future__ import annotations

import argparse
import re
from pathlib import Path


NUM_DCT = 12


CASE_RE = re.compile(r"^\[CASE\s+(\d+)\]\s+(.+)$")
VEC_RE = re.compile(r"^\s*(f32_mfcc|q31_mfcc\(q8\.23\)|q15_mfcc\(q8\.7\)|f16_mfcc)\s*=\s*(.+)$")


def parse_vec(s: str) -> list[float]:
    vals = [float(x) for x in s.strip().split()]
    if len(vals) != NUM_DCT:
        raise ValueError(f"Expected {NUM_DCT} values, got {len(vals)}: {s}")
    return vals


def parse_output(path: Path):
    cases = []
    current = None
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        m_case = CASE_RE.match(line)
        if m_case:
            if current is not None:
                cases.append(current)
            current = {
                "idx": int(m_case.group(1)),
                "name": m_case.group(2),
                "f32": None,
                "q31": None,
                "q15": None,
                "f16": None,
            }
            continue

        if current is None:
            continue
        m_vec = VEC_RE.match(line)
        if not m_vec:
            continue

        key = m_vec.group(1)
        vals = parse_vec(m_vec.group(2))
        if key == "f32_mfcc":
            current["f32"] = vals
        elif key.startswith("q31_mfcc"):
            current["q31"] = vals
        elif key.startswith("q15_mfcc"):
            current["q15"] = vals
        elif key == "f16_mfcc":
            current["f16"] = vals

    if current is not None:
        cases.append(current)

    cases.sort(key=lambda c: c["idx"])
    return cases


def emit_header(cases, out: Path):
    has_f16 = all(c["f16"] is not None for c in cases)
    lines: list[str] = []
    lines.append("/* Auto-generated by scripts/gen_mfcc_reference_from_output.py. */")
    lines.append("/* Source: runtime output from target/spike execution. */")
    lines.append("")
    lines.append("#ifndef MFCC_REFERENCE_DATA_H")
    lines.append("#define MFCC_REFERENCE_DATA_H")
    lines.append("")
    lines.append(f"#define MFCC_REF_NUM_CASES {len(cases)}")
    lines.append(f"#define MFCC_REF_NUM_DCT {NUM_DCT}")
    lines.append("#define MFCC_REF_HAS_F32 1")
    lines.append("#define MFCC_REF_HAS_Q31 1")
    lines.append("#define MFCC_REF_HAS_Q15 1")
    lines.append(f"#define MFCC_REF_HAS_F16 {1 if has_f16 else 0}")
    lines.append("")
    lines.append("#define MFCC_REF_F32_TOL 0.250000f")
    lines.append("#define MFCC_REF_Q31_TOL 0.050000f")
    lines.append("#define MFCC_REF_Q15_TOL 0.250000f")
    lines.append("#define MFCC_REF_F16_TOL 0.050000f")
    lines.append("")
    lines.append("static const char *const g_mfcc_ref_case_names[MFCC_REF_NUM_CASES] = {")
    for c in cases:
        lines.append(f'  "{c["name"]}",')
    lines.append("};")
    lines.append("")

    def emit_arr(name: str, key: str):
        lines.append(f"static const float g_mfcc_ref_{name}[MFCC_REF_NUM_CASES][MFCC_REF_NUM_DCT] = {{")
        for c in cases:
            row = ", ".join(f"{v:.9f}f" for v in c[key])
            lines.append(f'  /* {c["name"]} */')
            lines.append(f"  {{ {row} }},")
        lines.append("};")
        lines.append("")

    emit_arr("f32", "f32")
    emit_arr("q31", "q31")
    emit_arr("q15", "q15")
    if has_f16:
        emit_arr("f16", "f16")

    lines.append("#endif /* MFCC_REFERENCE_DATA_H */")
    lines.append("")
    out.write_text("\n".join(lines), encoding="utf-8")


def main():
    ap = argparse.ArgumentParser(description="Generate mfcc per-type golden header from output.txt")
    ap.add_argument(
        "--in",
        dest="inp",
        type=Path,
        default=Path(__file__).resolve().parents[1] / "output.txt",
        help="Path to mfcc-test output log",
    )
    ap.add_argument(
        "--out",
        type=Path,
        default=Path(__file__).resolve().parents[1] / "include" / "mfcc_reference_data.h",
        help="Header output path",
    )
    args = ap.parse_args()

    cases = parse_output(args.inp)
    if not cases:
        raise SystemExit(f"No test cases parsed from {args.inp}")

    required = ("f32", "q31", "q15")
    for c in cases:
        for k in required:
            if c[k] is None:
                raise SystemExit(f"Missing {k} for case {c['idx']} ({c['name']})")

    emit_header(cases, args.out)
    print(f"Wrote {args.out} from {args.inp}")


if __name__ == "__main__":
    main()
