#ifndef SIMPLE_CONV_BENCH_MODE_CONFIG_H
#define SIMPLE_CONV_BENCH_MODE_CONFIG_H

/*
 * Set each mode to 1 to run it, or 0 to disable it.
 */
#define SIMPLE_CONV_RUN_ACCELERATOR_MMIO 1
#define SIMPLE_CONV_RUN_SCALAR_REFERENCE 0
#define SIMPLE_CONV_RUN_RVV_REFERENCE    0
#define SIMPLE_CONV_RUN_ACCELERATOR_DMA  0

#endif /* SIMPLE_CONV_BENCH_MODE_CONFIG_H */
