#ifndef TINYSPEECH_MC_BENCH_CONFIG_H
#define TINYSPEECH_MC_BENCH_CONFIG_H

#include <stdint.h>

#ifndef TINYSPEECH_MC_TARGET_FREQUENCY_HZ
#define TINYSPEECH_MC_TARGET_FREQUENCY_HZ 500000000ULL
#endif

// 0: single-frequency mode
// 1: iterate over TINYSPEECH_MC_PLL_FREQ_LIST
#ifndef TINYSPEECH_MC_ENABLE_PLL_SWEEP
#define TINYSPEECH_MC_ENABLE_PLL_SWEEP 0
#endif

#ifndef TINYSPEECH_MC_PLL_SWEEP_SLEEP_MS
#define TINYSPEECH_MC_PLL_SWEEP_SLEEP_MS 10000u
#endif

// Comma-separated list used when TINYSPEECH_MC_ENABLE_PLL_SWEEP=1
// #define TINYSPEECH_MC_PLL_FREQ_LIST 50000000ULL, 150000000ULL, 250000000ULL
#ifndef TINYSPEECH_MC_PLL_FREQ_LIST
#define TINYSPEECH_MC_PLL_FREQ_LIST \
  50000000ULL, \
  150000000ULL, \
  250000000ULL, \
  350000000ULL
#endif

#ifndef TINYSPEECH_MC_ENABLE_MULTICORE
#define TINYSPEECH_MC_ENABLE_MULTICORE 1
#endif

// Output-channel split points for 2-core fixed-shape INT8 kernels.
// These are defaults; runtime autotune may override.
#ifndef TINYSPEECH_MC_CONV2_OC_SPLIT
#define TINYSPEECH_MC_CONV2_OC_SPLIT 24
#endif

#ifndef TINYSPEECH_MC_CONV3_OC_SPLIT
#define TINYSPEECH_MC_CONV3_OC_SPLIT 48
#endif

// Optional startup autotune for multicore split points.
// Uses first N inference cases to pick best (conv2,conv3) split pair.
#ifndef TINYSPEECH_MC_AUTOTUNE_SPLITS
#define TINYSPEECH_MC_AUTOTUNE_SPLITS 0
#endif

#ifndef TINYSPEECH_MC_AUTOTUNE_CASES
#define TINYSPEECH_MC_AUTOTUNE_CASES 8
#endif

#ifndef TINYSPEECH_MC_CONV2_OC_SPLIT_CANDIDATES
#define TINYSPEECH_MC_CONV2_OC_SPLIT_CANDIDATES 16, 20, 24, 28, 32
#endif

#ifndef TINYSPEECH_MC_CONV3_OC_SPLIT_CANDIDATES
#define TINYSPEECH_MC_CONV3_OC_SPLIT_CANDIDATES 32, 40, 48, 56, 64
#endif

// Optional memory placement hooks (disabled by default for portability).
// FC weight storage mode:
//   0 = local DRAM (.bss), no mapped staging
//   1 = mapped scratchpad (TINYSPEECH_MC_SCRATCHPAD_BASE + FC offset)
//   2 = mapped core0 TCM (TINYSPEECH_MC_CORE0_TCM_BASE + FC offset)
#ifndef TINYSPEECH_MC_FC_STORAGE_MODE
#define TINYSPEECH_MC_FC_STORAGE_MODE 0
#endif

#ifndef TINYSPEECH_MC_SCRATCHPAD_BYTES
#define TINYSPEECH_MC_SCRATCHPAD_BYTES (64u * 1024u)
#endif

#ifndef TINYSPEECH_MC_TCM_BYTES
#define TINYSPEECH_MC_TCM_BYTES (8u * 1024u)
#endif

#ifndef TINYSPEECH_MC_SCRATCHPAD_FC_OFFSET
#define TINYSPEECH_MC_SCRATCHPAD_FC_OFFSET 0u
#endif

#ifndef TINYSPEECH_MC_CORE0_TCM_FC_OFFSET
#define TINYSPEECH_MC_CORE0_TCM_FC_OFFSET 0u
#endif

#ifndef TINYSPEECH_MC_SCRATCHPAD_BASE
#define TINYSPEECH_MC_SCRATCHPAD_BASE 0x08000000UL
#endif

#ifndef TINYSPEECH_MC_CORE0_TCM_BASE
#define TINYSPEECH_MC_CORE0_TCM_BASE 0x08010000UL
#endif

#ifndef TINYSPEECH_MC_CORE1_TCM_BASE
#define TINYSPEECH_MC_CORE1_TCM_BASE 0x08012000UL
#endif

#endif
