#ifndef C2C_BEARLY_KWS_ROLLING_CONFIG_H
#define C2C_BEARLY_KWS_ROLLING_CONFIG_H

#include <stdio.h>

#include "chip_config.h"
#include "kws_rolling_proto.h"

#ifndef KWS_BEARLY_ROLLING_LOG_ENABLE
#define KWS_BEARLY_ROLLING_LOG_ENABLE 1
#endif

#if KWS_BEARLY_ROLLING_LOG_ENABLE
#define KWS_BEARLY_ROLLING_LOG(...) do { printf(__VA_ARGS__); } while (0)
#else
#define KWS_BEARLY_ROLLING_LOG(...) do { } while (0)
#endif

#ifndef KWS_BEARLY_ROLLING_TARGET_FREQUENCY_HZ
#define KWS_BEARLY_ROLLING_TARGET_FREQUENCY_HZ 500000000ULL
#endif

#ifndef KWS_BEARLY_ROLLING_SHM_BASE
#define KWS_BEARLY_ROLLING_SHM_BASE KWS_ROLLING_SHARED_BASE_ADDR
#endif

#ifndef KWS_BEARLY_ROLLING_SHM_BYTES
#define KWS_BEARLY_ROLLING_SHM_BYTES KWS_ROLLING_SHARED_BYTES
#endif

#ifndef KWS_BEARLY_ROLLING_COMMIT_SEQ_ADDR
#define KWS_BEARLY_ROLLING_COMMIT_SEQ_ADDR KWS_ROLLING_COMMIT_SEQ_ADDR
#endif

#ifndef KWS_BEARLY_ROLLING_FRAME_ADDR
#define KWS_BEARLY_ROLLING_FRAME_ADDR KWS_ROLLING_FRAME_ADDR
#endif

#ifndef KWS_BEARLY_ROLLING_WAIT_LOG_EVERY
#define KWS_BEARLY_ROLLING_WAIT_LOG_EVERY 200000u
#endif

#ifndef KWS_BEARLY_ROLLING_RX_LOG_EVERY
#define KWS_BEARLY_ROLLING_RX_LOG_EVERY 1u
#endif

#ifndef KWS_BEARLY_ROLLING_INFER_LOG_EVERY
#define KWS_BEARLY_ROLLING_INFER_LOG_EVERY 1u
#endif

#ifndef KWS_BEARLY_ROLLING_PRINT_LAYER_CYCLES
#define KWS_BEARLY_ROLLING_PRINT_LAYER_CYCLES 1u
#endif

#ifndef KWS_BEARLY_ROLLING_CLEAR_SHM_ON_BOOT
#define KWS_BEARLY_ROLLING_CLEAR_SHM_ON_BOOT 0u
#endif

#ifndef KWS_BEARLY_ROLLING_CACHE_LINE_BYTES
#define KWS_BEARLY_ROLLING_CACHE_LINE_BYTES 64u
#endif

#ifndef KWS_BEARLY_ROLLING_CACHE_EVICT_BYTES
#define KWS_BEARLY_ROLLING_CACHE_EVICT_BYTES (256u * 1024u)
#endif

#ifndef KWS_BEARLY_ROLLING_USE_THREADLIB
#define KWS_BEARLY_ROLLING_USE_THREADLIB 1
#endif

#ifndef KWS_BEARLY_ROLLING_TCM_BASE
#define KWS_BEARLY_ROLLING_TCM_BASE TCM_BASE
#endif

#ifndef KWS_BEARLY_ROLLING_TCM_BYTES
#define KWS_BEARLY_ROLLING_TCM_BYTES 0x2000u
#endif

#ifndef KWS_BEARLY_ROLLING_TCM_WINDOW_OFFSET
#define KWS_BEARLY_ROLLING_TCM_WINDOW_OFFSET 0x1000u
#endif

#define KWS_BEARLY_ROLLING_TCM_WINDOW_ADDR \
  (KWS_BEARLY_ROLLING_TCM_BASE + KWS_BEARLY_ROLLING_TCM_WINDOW_OFFSET)

#endif /* C2C_BEARLY_KWS_ROLLING_CONFIG_H */
