#ifndef C2C_TRANSFER_DSP_CONFIG_H
#define C2C_TRANSFER_DSP_CONFIG_H

#include <stdio.h>

#include "chip_config.h"
#include "transfer_proto.h"

#ifndef C2C_TRANSFER_DSP_LOG_ENABLE
#define C2C_TRANSFER_DSP_LOG_ENABLE 1
#endif

#if C2C_TRANSFER_DSP_LOG_ENABLE
#define C2C_TRANSFER_DSP_LOG(...) do { printf(__VA_ARGS__); } while (0)
#else
#define C2C_TRANSFER_DSP_LOG(...) do { } while (0)
#endif

#ifndef C2C_TRANSFER_DSP_TARGET_FREQUENCY_HZ
#define C2C_TRANSFER_DSP_TARGET_FREQUENCY_HZ 500000000ULL
#endif

#ifndef C2C_TRANSFER_DSP_SHARED_BASE
#define C2C_TRANSFER_DSP_SHARED_BASE TRANSFER_SHARED_BASE_ADDR
#endif

#ifndef C2C_TRANSFER_DSP_SHARED_BYTES
#define C2C_TRANSFER_DSP_SHARED_BYTES TRANSFER_SHARED_BYTES
#endif

#ifndef C2C_TRANSFER_DSP_MAILBOX_ADDR
#define C2C_TRANSFER_DSP_MAILBOX_ADDR C2C_TRANSFER_DSP_SHARED_BASE
#endif

#ifndef C2C_TRANSFER_DSP_NUM_PACKETS
#define C2C_TRANSFER_DSP_NUM_PACKETS 48u
#endif

#ifndef C2C_TRANSFER_DSP_INTERVAL_CYCLES
#define C2C_TRANSFER_DSP_INTERVAL_CYCLES 1000000ULL
#endif

#ifndef C2C_TRANSFER_DSP_STARTUP_DELAY_CYCLES
#define C2C_TRANSFER_DSP_STARTUP_DELAY_CYCLES 4000000ULL
#endif

#ifndef C2C_TRANSFER_DSP_CACHE_LINE_BYTES
#define C2C_TRANSFER_DSP_CACHE_LINE_BYTES 64u
#endif

#ifndef C2C_TRANSFER_DSP_CACHE_EVICT_BYTES
#define C2C_TRANSFER_DSP_CACHE_EVICT_BYTES (256u * 1024u)
#endif

#ifndef C2C_TRANSFER_DSP_CACHE_EVICT_PASSES
#define C2C_TRANSFER_DSP_CACHE_EVICT_PASSES 3u
#endif

#endif /* C2C_TRANSFER_DSP_CONFIG_H */
