add_subdirectory(dsp-kws)
add_subdirectory(bearly-kws)
add_subdirectory(dsp-kws-rolling)
add_subdirectory(bearly-kws-rolling)
add_subdirectory(bearly-kws-llama)
add_subdirectory(dsp-i2s-test)
add_subdirectory(dsp-simpletest)
add_subdirectory(bearly-simpletest)
add_subdirectory(c2c-measure)
add_subdirectory(hello-wfi)
add_subdirectory(dsp-hello-wfi)
add_subdirectory(bearly-hello-wfi)
add_subdirectory(c2c-transfer-dsp)
add_subdirectory(c2c-transfer-bearly)
