#ifndef C2C_DSP_KWS_ROLLING_CONFIG_H
#define C2C_DSP_KWS_ROLLING_CONFIG_H

#include <stdio.h>

#include "chip_config.h"
#include "kws_rolling_proto.h"

#ifndef KWS_DSP_ROLLING_LOG_ENABLE
#define KWS_DSP_ROLLING_LOG_ENABLE 1
#endif

#if KWS_DSP_ROLLING_LOG_ENABLE
#define KWS_DSP_ROLLING_LOG(...) do { printf(__VA_ARGS__); } while (0)
#else
#define KWS_DSP_ROLLING_LOG(...) do { } while (0)
#endif

#ifndef KWS_DSP_ROLLING_TARGET_FREQUENCY_HZ
#define KWS_DSP_ROLLING_TARGET_FREQUENCY_HZ 500000000ULL
#endif

#ifndef KWS_DSP_ROLLING_SHARED_BASE
#define KWS_DSP_ROLLING_SHARED_BASE KWS_ROLLING_SHARED_BASE_ADDR
#endif

#ifndef KWS_DSP_ROLLING_SHARED_BYTES
#define KWS_DSP_ROLLING_SHARED_BYTES KWS_ROLLING_SHARED_BYTES
#endif

#ifndef KWS_DSP_ROLLING_COMMIT_SEQ_ADDR
#define KWS_DSP_ROLLING_COMMIT_SEQ_ADDR KWS_ROLLING_COMMIT_SEQ_ADDR
#endif

#ifndef KWS_DSP_ROLLING_FRAME_ADDR
#define KWS_DSP_ROLLING_FRAME_ADDR KWS_ROLLING_FRAME_ADDR
#endif

#ifndef KWS_DSP_ROLLING_FRAMES_PER_CASE
#define KWS_DSP_ROLLING_FRAMES_PER_CASE KWS_FRAMES_PER_CASE
#endif

#ifndef KWS_DSP_ROLLING_STEADY_FRAME_IDX
#define KWS_DSP_ROLLING_STEADY_FRAME_IDX (KWS_DSP_ROLLING_FRAMES_PER_CASE - 1u)
#endif

#ifndef KWS_DSP_ROLLING_MFCC_QUANT_SCALE
#define KWS_DSP_ROLLING_MFCC_QUANT_SCALE 4.0f
#endif

#ifndef KWS_DSP_ROLLING_MFCC_QUANT_ZERO
#define KWS_DSP_ROLLING_MFCC_QUANT_ZERO 0.0f
#endif

#ifndef KWS_DSP_ROLLING_SIGNAL_HOP_SAMPLES
#define KWS_DSP_ROLLING_SIGNAL_HOP_SAMPLES 160u
#endif

#ifndef KWS_DSP_ROLLING_USE_THREADLIB
#define KWS_DSP_ROLLING_USE_THREADLIB 0
#endif

#ifndef KWS_DSP_ROLLING_SEND_INTERVAL_CYCLES
#define KWS_DSP_ROLLING_SEND_INTERVAL_CYCLES 0ULL
#endif

#ifndef KWS_DSP_ROLLING_LOG_EVERY
#define KWS_DSP_ROLLING_LOG_EVERY 1u
#endif

#ifndef KWS_DSP_ROLLING_DEBUG_WRITE_ENABLE
#define KWS_DSP_ROLLING_DEBUG_WRITE_ENABLE 0
#endif

#ifndef KWS_DSP_ROLLING_CACHE_LINE_BYTES
#define KWS_DSP_ROLLING_CACHE_LINE_BYTES 64u
#endif

#ifndef KWS_DSP_ROLLING_CACHE_EVICT_BYTES
#define KWS_DSP_ROLLING_CACHE_EVICT_BYTES (256u * 1024u)
#endif

#endif /* C2C_DSP_KWS_ROLLING_CONFIG_H */
