#!/usr/bin/env python3
"""
generate_test_inputs.py - Generate C header with embedded test images

Downloads sample images, preprocesses them with MobileNetV2 transforms,
and outputs a C header file with the data as float arrays.
"""

import urllib.request
import os
import sys

def main():
    try:
        import torch
        from torchvision.models import MobileNet_V2_Weights
        from PIL import Image
        import numpy as np
        from io import BytesIO
    except ImportError as e:
        print(f"Error: {e}")
        print("Install: pip install torch torchvision pillow numpy")
        sys.exit(1)

    # Sample images with known ImageNet classes
    # Using public domain / freely available images
    TEST_IMAGES = [
        {
            "name": "cat",
            "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Cat03.jpg/1200px-Cat03.jpg",
            "expected_class": 282,  # tiger cat
            "description": "Orange tabby cat"
        },
        {
            "name": "dog", 
            "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/26/YellowLabradorLooking_new.jpg/1200px-YellowLabradorLooking_new.jpg",
            "expected_class": 208,  # Labrador retriever
            "description": "Yellow Labrador retriever"
        },
    ]

    # Get transforms
    weights = MobileNet_V2_Weights.DEFAULT
    transforms = weights.transforms()

    print("=" * 60)
    print("Generating Test Inputs Header")
    print("=" * 60)
    print()

    output_path = "build_artifacts/test_inputs.h"
    
    with open(output_path, "w") as f:
        f.write("/*\n")
        f.write(" * test_inputs.h - Preprocessed test images for MobileNetV2\n")
        f.write(" * Auto-generated by generate_test_inputs.py\n")
        f.write(" *\n")
        f.write(" * Each image is preprocessed with official MobileNetV2 transforms:\n")
        f.write(" *   - Resize to 232 (shorter edge)\n")
        f.write(" *   - Center crop to 224x224\n")
        f.write(f" *   - Normalize: mean={list(transforms.mean)}, std={list(transforms.std)}\n")
        f.write(" */\n\n")
        f.write("#ifndef TEST_INPUTS_H\n")
        f.write("#define TEST_INPUTS_H\n\n")

        for i, img_info in enumerate(TEST_IMAGES):
            name = img_info["name"]
            url = img_info["url"]
            expected = img_info["expected_class"]
            desc = img_info["description"]
            
            print(f"[{i+1}/{len(TEST_IMAGES)}] Downloading {name}...")
            
            try:
                # Download image
                req = urllib.request.Request(url, headers={'User-Agent': 'Mozilla/5.0'})
                with urllib.request.urlopen(req, timeout=30) as response:
                    img_data = response.read()
                
                img = Image.open(BytesIO(img_data)).convert("RGB")
                print(f"    Original size: {img.size}")
                
                # Preprocess
                tensor = transforms(img).unsqueeze(0)  # Add batch dim
                arr = tensor.numpy().astype(np.float32).flatten()
                
                print(f"    Tensor shape: {tuple(tensor.shape)}")
                print(f"    Expected class: {expected} ({desc})")
                
                # Write to header
                f.write(f"/* Test image: {name}\n")
                f.write(f" * Source: {url}\n")
                f.write(f" * Description: {desc}\n")
                f.write(f" * Expected class: {expected}\n")
                f.write(f" */\n")
                f.write(f"static const float test_input_{name}[1][3][224][224] = {{{{\n")
                
                # Write data in chunks for readability
                chunk_size = 8
                for j in range(0, len(arr), chunk_size):
                    chunk = arr[j:j+chunk_size]
                    line = ", ".join(f"{v:.8f}f" for v in chunk)
                    if j + chunk_size < len(arr):
                        f.write(f"    {line},\n")
                    else:
                        f.write(f"    {line}\n")
                
                f.write("}};\n\n")
                print(f"    ✓ Written to header\n")
                
            except Exception as e:
                print(f"    ✗ Failed: {e}\n")
                continue

        # Write expected classes array
        f.write("/* Expected class indices for verification */\n")
        f.write(f"static const int expected_classes[] = {{\n")
        for img_info in TEST_IMAGES:
            f.write(f"    {img_info['expected_class']},  /* {img_info['name']} - {img_info['description']} */\n")
        f.write("};\n\n")
        
        f.write("/* Image names for printing */\n")
        f.write("static const char* test_image_names[] = {\n")
        for img_info in TEST_IMAGES:
            f.write(f'    "{img_info["name"]}",\n')
        f.write("};\n\n")
        
        f.write(f"#define NUM_TEST_IMAGES {len(TEST_IMAGES)}\n\n")
        f.write("#endif /* TEST_INPUTS_H */\n")

    file_size = os.path.getsize(output_path)
    print("=" * 60)
    print(f"✅ Generated {output_path}")
    print(f"   Size: {file_size / 1024 / 1024:.1f} MB")
    print(f"   Contains {len(TEST_IMAGES)} test images")
    print("=" * 60)

if __name__ == "__main__":
    main()
