#!/usr/bin/env python3
"""Generate deterministic input/kernel datasets for 1D-conv benchmarks."""

from __future__ import annotations

import argparse
import math
import random
import struct
from pathlib import Path
from typing import List


def f32_to_u32(x: float) -> int:
    return struct.unpack("<I", struct.pack("<f", float(x)))[0]


def clamp_f32(x: float, lo: float = -8.0, hi: float = 8.0) -> float:
    if x < lo:
        return lo
    if x > hi:
        return hi
    return x


def build_input_dataset(kind: int, n: int, rng: random.Random) -> List[float]:
    out: List[float] = []
    for i in range(n):
        t = float(i) / float(max(1, n - 1))
        if kind == 0:
            # Smooth audio-like composite waveform.
            x = (
                0.75 * math.sin(2.0 * math.pi * 3.0 * t)
                + 0.22 * math.cos(2.0 * math.pi * 9.0 * t)
                + 0.08 * math.sin(2.0 * math.pi * 31.0 * t)
            )
        elif kind == 1:
            # Chirp + envelope.
            phase = 2.0 * math.pi * (2.0 * t + 18.0 * t * t)
            env = 0.15 + 0.85 * (1.0 - abs(2.0 * t - 1.0))
            x = env * math.sin(phase)
        elif kind == 2:
            # Sparse impulse train with alternating sign.
            base = 0.02 * math.sin(2.0 * math.pi * 5.0 * t)
            if (i % 47) == 0:
                base += 0.95
            if (i % 91) == 0:
                base -= 0.85
            if (i % 2) == 1:
                base *= -1.0
            x = base
        elif kind == 3:
            # Uniform random with slight low-frequency trend.
            x = rng.uniform(-0.95, 0.95) + 0.10 * math.sin(2.0 * math.pi * 1.5 * t)
        else:
            # Fallback random mixture for additional datasets.
            x = (
                rng.uniform(-0.85, 0.85)
                + 0.30 * math.sin(2.0 * math.pi * (kind + 1) * t)
                + 0.05 * math.cos(2.0 * math.pi * (kind + 11) * t)
            )
        out.append(clamp_f32(x))
    return out


def build_kernel_dataset(kind: int, k: int, rng: random.Random) -> List[float]:
    values: List[float] = []
    center = (k - 1) / 2.0
    for i in range(k):
        x = (float(i) - center) / max(1.0, center)
        if kind == 0:
            # Edge detector-ish alternating response.
            v = ((-1.0) ** i) * (0.45 - 0.02 * i)
        elif kind == 1:
            # Gaussian-ish low-pass.
            v = math.exp(-2.2 * x * x)
        elif kind == 2:
            # Difference of Gaussians.
            v = math.exp(-2.0 * x * x) - 0.6 * math.exp(-8.0 * x * x)
        elif kind == 3:
            # Random signed kernel.
            v = rng.uniform(-1.0, 1.0)
        else:
            v = 0.45 * math.sin((kind + 1) * (i + 1)) + rng.uniform(-0.2, 0.2)
        values.append(v)

    # Normalize to keep dynamic range stable.
    l1 = sum(abs(v) for v in values)
    if l1 < 1.0e-9:
        return [0.0 for _ in values]
    scale = 1.0 / l1
    return [clamp_f32(v * scale) for v in values]


def format_u32_array(values: List[int], indent: str = "      ") -> str:
    lines: List[str] = []
    row: List[str] = []
    for idx, v in enumerate(values):
        row.append(f"0x{v:08X}u")
        if (idx + 1) % 8 == 0:
            lines.append(indent + ", ".join(row) + ",")
            row = []
    if row:
        lines.append(indent + ", ".join(row) + ",")
    return "\n".join(lines)


def render_header(max_n: int, max_k: int, num_datasets: int, seed: int) -> str:
    rng = random.Random(seed)
    names = [
        "sine_mix",
        "chirp_env",
        "sparse_impulse",
        "random_trend",
    ]
    while len(names) < num_datasets:
        names.append(f"synthetic_{len(names)}")

    inputs_bits: List[List[int]] = []
    kernels_bits: List[List[int]] = []

    for ds in range(num_datasets):
        local_rng = random.Random(seed + ds * 7919)
        inp = build_input_dataset(ds, max_n, local_rng)
        ker = build_kernel_dataset(ds, max_k, local_rng)
        inputs_bits.append([f32_to_u32(x) for x in inp])
        kernels_bits.append([f32_to_u32(x) for x in ker])

    out: List[str] = []
    out.append("#ifndef CONV1D_BENCH_GENERATED_DATA_H")
    out.append("#define CONV1D_BENCH_GENERATED_DATA_H")
    out.append("")
    out.append("#include <stdint.h>")
    out.append("")
    out.append(f"#define CONV_BENCH_GENERATED_MAX_N {max_n}u")
    out.append(f"#define CONV_BENCH_GENERATED_MAX_K {max_k}u")
    out.append(f"#define CONV_BENCH_GENERATED_NUM_DATASETS {num_datasets}u")
    out.append("")
    out.append(f"// Generated by gen_conv_data.py (seed={seed}).")
    out.append("static const char *const g_conv_bench_dataset_names[CONV_BENCH_GENERATED_NUM_DATASETS] = {")
    for i in range(num_datasets):
        comma = "," if i + 1 < num_datasets else ""
        out.append(f'  "{names[i]}"{comma}')
    out.append("};")
    out.append("")

    out.append(
        "static const uint32_t g_conv_bench_generated_inputs"
        "[CONV_BENCH_GENERATED_NUM_DATASETS][CONV_BENCH_GENERATED_MAX_N] = {"
    )
    for ds in range(num_datasets):
        comma = "," if ds + 1 < num_datasets else ""
        out.append("  {")
        out.append(format_u32_array(inputs_bits[ds]))
        out.append(f"  }}{comma}")
    out.append("};")
    out.append("")

    out.append(
        "static const uint32_t g_conv_bench_generated_kernels"
        "[CONV_BENCH_GENERATED_NUM_DATASETS][CONV_BENCH_GENERATED_MAX_K] = {"
    )
    for ds in range(num_datasets):
        comma = "," if ds + 1 < num_datasets else ""
        out.append("  {")
        out.append(format_u32_array(kernels_bits[ds]))
        out.append(f"  }}{comma}")
    out.append("};")
    out.append("")
    out.append("#endif")
    out.append("")

    return "\n".join(out)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--max-n", type=int, default=2048)
    parser.add_argument("--max-k", type=int, default=16)
    parser.add_argument("--num-datasets", type=int, default=4)
    parser.add_argument("--seed", type=int, default=12345)
    parser.add_argument(
        "--out",
        type=Path,
        default=Path("dsp25-bmarks/1dconv-bmarks/include/bench_generated_data.h"),
    )
    args = parser.parse_args()

    if args.max_n <= 0:
        raise ValueError("--max-n must be > 0")
    if args.max_k <= 0:
        raise ValueError("--max-k must be > 0")
    if args.num_datasets <= 0:
        raise ValueError("--num-datasets must be > 0")

    content = render_header(args.max_n, args.max_k, args.num_datasets, args.seed)
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(content)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
